// auto-generated from auto_gen.sh, DO NOT EDIT!

// REMOVE_COMMAS
#define AG_REMOVE_COMMAS_0(a, ...) a AG_REMOVE_COMMAS_1(__VA_ARGS__)
#define AG_REMOVE_COMMAS_1(a, ...) a AG_REMOVE_COMMAS_2(__VA_ARGS__)
#define AG_REMOVE_COMMAS_2(a, ...) a AG_REMOVE_COMMAS_3(__VA_ARGS__)
#define AG_REMOVE_COMMAS_3(a, ...) a AG_REMOVE_COMMAS_4(__VA_ARGS__)
#define AG_REMOVE_COMMAS_4(a, ...) a AG_REMOVE_COMMAS_5(__VA_ARGS__)
#define AG_REMOVE_COMMAS_5(a, ...) a AG_REMOVE_COMMAS_6(__VA_ARGS__)
#define AG_REMOVE_COMMAS_6(a, ...) a AG_REMOVE_COMMAS_7(__VA_ARGS__)
#define AG_REMOVE_COMMAS_7(a, ...) a AG_REMOVE_COMMAS_8(__VA_ARGS__)
#define AG_REMOVE_COMMAS_8(a, ...) a AG_REMOVE_COMMAS_9(__VA_ARGS__)
#define AG_REMOVE_COMMAS_9(a, ...) a AG_REMOVE_COMMAS_10(__VA_ARGS__)
#define AG_REMOVE_COMMAS_10(a, ...) a AG_REMOVE_COMMAS_11(__VA_ARGS__)
#define AG_REMOVE_COMMAS_11(a, ...) a AG_REMOVE_COMMAS_12(__VA_ARGS__)
#define AG_REMOVE_COMMAS_12(a, ...) a AG_REMOVE_COMMAS_13(__VA_ARGS__)
#define AG_REMOVE_COMMAS_13(a, ...) a AG_REMOVE_COMMAS_14(__VA_ARGS__)
#define AG_REMOVE_COMMAS_14(a, ...) a AG_REMOVE_COMMAS_15(__VA_ARGS__)
#define AG_REMOVE_COMMAS_15(a, ...) a AG_REMOVE_COMMAS_16(__VA_ARGS__)
#define AG_REMOVE_COMMAS_16(a, ...) a AG_REMOVE_COMMAS_17(__VA_ARGS__)
#define AG_REMOVE_COMMAS_17(a, ...) a AG_REMOVE_COMMAS_18(__VA_ARGS__)
#define AG_REMOVE_COMMAS_18(a, ...) a AG_REMOVE_COMMAS_19(__VA_ARGS__)
#define AG_REMOVE_COMMAS_19(a, ...) a AG_REMOVE_COMMAS_20(__VA_ARGS__)
#define AG_REMOVE_COMMAS_20(a, ...) a AG_REMOVE_COMMAS_21(__VA_ARGS__)
#define AG_REMOVE_COMMAS_21(a, ...) a AG_REMOVE_COMMAS_22(__VA_ARGS__)
#define AG_REMOVE_COMMAS_22(a, ...) a AG_REMOVE_COMMAS_23(__VA_ARGS__)
#define AG_REMOVE_COMMAS_23(a, ...) a AG_REMOVE_COMMAS_24(__VA_ARGS__)
#define AG_REMOVE_COMMAS_24(a, ...) a

